---
- hosts: dbms
  tags: database
  become: true
  roles:
    - role: dbms

- hosts: backend
  tags: php-fpm
  become: true
  roles:
    - role: backend

- hosts: nginx
  tags: nginx
  become: true
  roles:
    - role: nginx

- hosts: nginx1
  tags: nginx1
  become: true
  tasks:
    - name: Configuring keppalive Master
      lineinfile: dest=/etc/keepalived/keepalived.conf
                  regexp='state BACKUP'
                  line='    state MASTER'
                  state=present
    - name: Restart keepalived
      service: 
        name: keepalived
        state: restarted

